Enhancements
blockademy/logging-lib pull request #1
Opened 2024-11-29 16:59 UTC by romangarcia

2024-12-03 10:32 UTC, gonzalob requested changes

2024-12-03 10:32 UTC, gonzalob commented on __tests__/LoggerFactory.test.ts
> +        expect(fileContent).toContain('test');
¿cómo verifican estos expects que se esté usando pretty?

2024-12-03 10:32 UTC, gonzalob commented on __tests__/LoggerFactory.test.ts
> +        expect(fileContent).toContain('INFO');
¿no necesitás devolver el último expect?

2024-12-03 10:32 UTC, gonzalob commented on __tests__/LoggerFactory.test.ts
> +        expect(fileContent).toContain('will be logged');
¿poner distintos strings en los atributos, y distintos expects, no te asegura que se impriman todos? esto pasa con que sólo se imprima una vez.

2024-12-03 13:03 UTC, romangarcia commented on __tests__/LoggerFactory.test.ts
> +        expect(fileContent).toContain('INFO');
entiendo que no, que si haces un await ya estas devolviendo una promise

2024-12-04 12:53 UTC, gonzalob approved these changes

2024-12-04 13:19 UTC, merged